### PR TITLE
Add Github Pages hosted documentation.

### PR DESCRIPTION
**Pull request by LeeBergstrand**
Hi @apmasell ,

I'm a new bioinformatics Masters student in the Josh Neufeld lab. Josh, @jmtsuji and I have decided to start moving ```neufeldserver``` behind the UofW firewall for security reasons. This would, generally, eliminate the ability for it host web content. We noticed that some of pandaseqs documentation is still hosted there. One option we have for free hosting of this documentation is [Github Pages](https://pages.github.com). In this pull request I have moved the documentation originally hosted on ```neufeldserver``` to a ```docs``` folder in this repo. 

All you would need to do is turn on GitHub pages for this repo and redirect some urls in the readme and wiki to Github pages address rather than ```neufeldserver``` address.

If you could review the documentation folder to make sure I got all the documentation that would be great as well.

Cheers,

Lee

### CODE REVIEW

**Comment by LeeBergstrand** [comment]
@apmasell I noticed that we may need to move some other files:

Looking at your travis.yml

```yml
before_script:
  - test "x$GET_WIN" = x || wget -O- http://neufeldserver.uwaterloo.ca/~apmasell/pandaseq-windeps.tar.bz2 | tar xj
```

**Comment by apmasell** [comment]
Yeah, the Windows build dependencies can also go in the S3 bucket.

**Comment by LeeBergstrand** [comment]
> The man page should say, but generated content doesn't belong in git. Can we set up an S3 bucket to hold that content and the Travis build process and dump a copy of the HTML-ified man page there? I did this for a different project: BoutrosLaboratory/bamql@933666e

I didn't realize that the man page was being autogenerated. Lets go with this.

**Comment by LeeBergstrand** [comment]
@apmasell Moving this to an issue.

**Pull request closed without merging**
